# Usa l'immagine "full" di Node.js, che contiene Python e altri tool.
FROM node:20

# Installa gli strumenti di compilazione necessari per moduli nativi come hnswlib-node
RUN apt-get update && apt-get install -y build-essential

# Procedi con il setup standard
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Esponi la porta su cui l'app ascolterà
EXPOSE 8080

# Definisci il comando di avvio
CMD [ "node", "server.js" ]