name: pesca_app
description: "Un nuovo progetto Flutter per le previsioni di pesca."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  lottie: ^3.3.2
  fl_chart: ^1.1.1
  http: ^1.5.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        # --- MODIFICATO PER CORRISPONDERE AI SUOI FILE ---
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic